### PR TITLE
Switch to GPL 3 license

### PR DESCRIPTION
**Pull request by SSoelvsten**
We should switch to another license than MIT, since we would want to require any research and further development on Adiar  to also be made public. That is, this research project is intended to be in and stay within the public domain. You may use it as you like in a commercial private product, but any development you do on Adiar itself should be given back to "us".

**Tasks to be done**
- [x] Replace the _License.md_ file.
- [x] Update _README.md_ file
- [x] Update _index.md_ in the documentation
- [x] Put license into all C++ files.
  - Large version in `adiar.h`
  - Smaller referential version in all other files

**Consent by other contributors** (see comments below)

- :grey_question: Anna Blume Jakobsen
- :+1: Asger Hautop Drewsen
- :+1: Mathias Weller Berg Thomasen
- :+1: Mathias Rav
- :-1: Jaco van de Pol
- :+1: Jakob Schneider

### CODE REVIEW

**Comment by jaschdoc** [comment]
All good, I approve :)

**Comment by Tyilo** [comment]
I approve :)

**Comment by Mortal** [comment]
I approve of the switch to GPL3.

**Comment by MathiasWeller42** [comment]
I approve of the switch to GPL3:)

**Comment by SSoelvsten** [comment]
The GPL 3 license does _taint_ the resulting binary of anyone who would use Adiar with said license, i.e. if they share that binary, then they have to disclose the source code too. Technically, since TPIE is licensed under GPL 3, then this is already a problem.

What I really want is to make that anyone who improves Adiar is also obliged to share it. Hence, the _Lesser_ General Public License is actually what we want to use. See pull request #197 instead.

**Pull request closed without merging**
