### PR TITLE
Add .clang-format

### PR DESCRIPTION
**Pull request by halvko**
After a bunch of testing, this Clang Format configuration is quite close to what is done _most of the time_ in this repository. The only thing I've found which it breaks consistently is when an UDT is instanciated inline, the braces are split:
```
struct bar
{ } foo;
```
becomes
```
struct bar
{
} foo;
```
and (maybe worse cause that's how it's often written in this project)
```
struct bar
{ }
// comment
foo;
```
becomes
```
struct bar
{
}
// comment
foo;
```
. This along with disallowing the rest of multiple operator seperated items in argument position to flow to the last line if they are neccesary to split giving:
```
throw invalid_argument("Adiar requires at least "
                       + std::to_string(minimum_memory / 1024 / 1024)
		       + " MiB of memory");
```
becomes
```
throw invalid_argument("Adiar requires at least "
                       + std::to_string(minimum_memory / 1024 / 1024) + " MiB of memory");
```

Except for that, all changes I've observed it making is within "normal" for the codebase. Currently (as of clang format 18) the first problem is unfixable - a PR to fix it had been stuck since 2020, and has since been closed. The second I have not been able to find a solution to.

In the name of not letting the perfect be the enemy of the good, I still propose adopting this. It "fixes" a lot of inconsistent formatting as it is now, and I think it is a nice developer experience to be able to write a piece of code, and have most of the formatting taken care of by a tool.

### CODE REVIEW

**Comment by halvko** [comment]
To try it out, checkout this branch, and call
```bash
clang-format <file-name> -i
```
to have it reformat <file-name>.

**Comment by SSoelvsten** [comment]
Great work. That would definitely be a great addition - especially when others than me actually want to contribute.

I tried to run it and found a few things. I can live with some other "compromises" to fix them.

**1. Indentation of Member list**
```
-    builder_ptr(const internal::node::uid_type &p,
-                const shared_ptr<const builder_shared> &sp)
-      : uid(p), builder_ref(sp)
-    { }
```
```
+    builder_ptr(const internal::node::uid_type& p, const shared_ptr<const builder_shared>& sp)
+        : uid(p), builder_ref(sp)
+    {}
```

Indentation is here *4* spaces rather than *2*.

**2. One-liner constructors**

Exhibit A:
```
-    builder() noexcept
-    { }
```
```
+    builder() noexcept {}
```

Exhibit B:
```
-    exec_policy(const access &am)
-      : _access_mode(am)
-    { }
```
```
+    exec_policy(const access& am) : _access_mode(am) {}
```

Can the constructors always have line breaks after the arguments and the member initialisation list?

**Line Breaks on boolean operations**

```
-      return this->memory_mode()  == ep.memory_mode()
-          && this->access_mode()  == ep.access_mode()
-          && this->quantify_alg() == ep.quantify_alg()
-        ;
```
```
+      return this->memory_mode() == ep.memory_mode() && this->access_mode() == ep.access_mode()
+          && this->quantify_alg() == ep.quantify_alg();
```

If there is a line break, then I would prefer it breaks all of them. The idea being, that the 'vertical' dimension is the conditions and the horizontal then their content.

**4. Weird 4-space indentations**

In *src/adiar/internal/algorithms/reduce.h*. Is this related with trying to align the statement with `return`?

```
       adiar_assert(!arcs.can_pull_internal()
-                   || current_map.old_uid == arcs.peek_internal().target(),
```
```
       adiar_assert(!arcs.can_pull_internal()
+                       || current_map.old_uid == arcs.peek_internal().target(),
                    "Mapping forwarded in sync with internal arcs");
```

And in *src/adiar/internal/algorithms/prod2.h*. Here, it adds an odd additional indentation.
```
   using prod_priority_queue_1_t =
-    levelized_node_priority_queue<prod2_request<0>, request_data_first_lt<prod2_request<0>>,
-                                  look_ahead,
-                                  mem_mode,
-                                  2,
-                                  0>;
```
```
   using prod_priority_queue_1_t =
+      levelized_node_priority_queue<prod2_request<0>,
+                                    request_data_first_lt<prod2_request<0>>,
+                                    look_ahead,
+                                    mem_mode,
+                                    2,
+                                    0>;
```

**Comment by SSoelvsten** [comment]
## Conflicting with Emacs

Overall the *GNU* style is Emacs-compatible. So, if there are settings in the *GNU* clang-format file that conflicts with this then the *GNU* setting would be the safest to use. The exception would be all settings that can be resolved with a 'newline' character (Emacs does not add newlines, but has an "intelligent" indentation). In general, I'm ok with being more GNU-like at the compromise of some parts of the codebase (which I indented manually).

**Indentation of Member list**
```
-    builder_ptr(const internal::node::uid_type &p,
-                const shared_ptr<const builder_shared> &sp)
-      : uid(p), builder_ref(sp)
-    { }
```
```
+    builder_ptr(const internal::node::uid_type& p, const shared_ptr<const builder_shared>& sp)
+        : uid(p), builder_ref(sp)
+    {}
```

Indentation is here *4* spaces rather than *2*.

**Comma in Member Initialisation List**

In *src/adiar/internal/data_structures/levelized_priority_queue.h*

```
-    levelized_priority_queue(tpie::memory_size_type memory_given, size_t max_size,
-                             [[maybe_unused]] statistics::levelized_priority_queue_t &stats)
-      : _max_size(max_size)
-      , _memory_given(memory_given)
-      , _memory_for_buckets(memory_given - _memory_occupied_by_merger - mem_overflow_queue(memory_given))
-      , _memory_occupied_by_overflow(mem_overflow_queue(memory_given))
-      , _overflow_queue(mem_overflow_queue(memory_given), max_size)
```
```
+    levelized_priority_queue(tpie::memory_size_type memory_given,
+                             size_t max_size,
+                             [[maybe_unused]] statistics::levelized_priority_queue_t& stats)
+        : _max_size(max_size),
+          _memory_given(memory_given),
+          _memory_for_buckets(memory_given - _memory_occupied_by_merger
+                              - mem_overflow_queue(memory_given)),
+          _memory_occupied_by_overflow(mem_overflow_queue(memory_given)),
+          _overflow_queue(mem_overflow_queue(memory_given), max_size)
```

Here, Emacs would de-indent all but the first member initialisation by two. This is why, I move the `,` to the start of the line, because then Emacs nicely aligns everything.

**Unexpected 4-space indentations**

In *src/adiar/internal/algorithms/reduce.h*. Is this related with trying to align the statement with `return`?

```
       adiar_assert(!arcs.can_pull_internal()
-                   || current_map.old_uid == arcs.peek_internal().target(),
```
```
       adiar_assert(!arcs.can_pull_internal()
+                       || current_map.old_uid == arcs.peek_internal().target(),
                    "Mapping forwarded in sync with internal arcs");
```

And in *src/adiar/internal/algorithms/prod2.h*. Here, it adds an odd additional indentation.
```
   using prod_priority_queue_1_t =
-    levelized_node_priority_queue<prod2_request<0>, request_data_first_lt<prod2_request<0>>,
-                                  look_ahead,
-                                  mem_mode,
-                                  2,
-                                  0>;
```
```
   using prod_priority_queue_1_t =
+      levelized_node_priority_queue<prod2_request<0>,
+                                    request_data_first_lt<prod2_request<0>>,
+                                    look_ahead,
+                                    mem_mode,
+                                    2,
+                                    0>;
```

And in *src/adiar/internal/data_structures/levelized_priority_queue.h*

```
     ////////////////////////////////////////////////////////////////////////////
     /// \brief Total number of data structures in Levelized Priority Queue.
     ////////////////////////////////////////////////////////////////////////////
     static constexpr size_t data_structures =
-      buckets * sorter_t::data_structures + priority_queue_t::data_structures;
```
```
     ////////////////////////////////////////////////////////////////////////////
     /// \brief Total number of data structures in Levelized Priority Queue.
     ////////////////////////////////////////////////////////////////////////////
     static constexpr size_t data_structures =
+        buckets * sorter_t::data_structures + priority_queue_t::data_structures;
```

**Struct Initialisation**

In *src/adiar/statistics.cpp*, the indentation on the struct misaligns with Emacs.

```
-    return {
-      // i/o
-      internal::stats_arc_file,
-      internal::stats_node_file,
-
-      // data structures
-      internal::stats_levelized_priority_queue,
-
-      // top-down sweeps
-      internal::stats_count,
-      internal::stats_equality,
-      internal::stats_intercut,
-      internal::stats_optmin,
-      internal::stats_prod2,
-      stats_prod3,
-      internal::stats_quantify,
-      internal::stats_select,
-
-      // bottom-up sweeps
-      internal::stats_reduce,
-
-      // other algorithms
-      internal::nested_sweeping::stats
-    };
```
```
+    return {// i/o
+            internal::stats_arc_file,
+            internal::stats_node_file,
+
+            // data structures
+            internal::stats_levelized_priority_queue,
+
+            // top-down sweeps
+            internal::stats_count,
+            internal::stats_equality,
+            internal::stats_intercut,
+            internal::stats_optmin,
+            internal::stats_prod2,
+            stats_prod3,
+            internal::stats_quantify,
+            internal::stats_select,
+
+            // bottom-up sweeps
+            internal::stats_reduce,
+
+            // other algorithms
+            internal::nested_sweeping::stats};
```

**Odd indentation for function call**

In *src/adiar/internal/data_structures/levelized_priority_queue.h*.

```
-    static_assert(ptr_uint64::max_label+1 > ptr_uint64::max_label,
-                  "'ptr_uint64::label_type' should leave a window of at least one above 'max_label'");
```
```
+    static_assert(
+        ptr_uint64::max_label + 1 > ptr_uint64::max_label,
+        "'ptr_uint64::label_type' should leave a window of at least one above 'max_label'");
```

Emacs would in this case even with the 'newline' added indent it up to the `(` parentheses.

**Comment by SSoelvsten** [comment]
## Other (Personal Preference)


**One-liner constructors**

In *src/adiar/builder.h*
```
-    builder() noexcept
-    { }
```
```
+    builder() noexcept {}
```

In *src/adiar/exec_policy.h*
```
-    exec_policy(const access &am)
-      : _access_mode(am)
-    { }
```
```
+    exec_policy(const access& am) : _access_mode(am) {}
```

Can the constructors always have line breaks after the arguments and the member initialisation list?

**Line Breaks on binary operations**

In *src/adiar/exec_policy.h*.

```
-      return this->memory_mode()  == ep.memory_mode()
-          && this->access_mode()  == ep.access_mode()
-          && this->quantify_alg() == ep.quantify_alg()
-        ;
```
```
+      return this->memory_mode() == ep.memory_mode() && this->access_mode() == ep.access_mode()
+          && this->quantify_alg() == ep.quantify_alg();
```

If there is a line break, then I would prefer it breaks all of them. The idea being, that the 'vertical' dimension is the conditions and the horizontal then their content. But, it is fair, if that is not possible.

Similarly, in *src/adiar/statistics.cpp*

```
     uintwide total_runs = internal::stats_prod2.trivial_file
-                        + internal::stats_prod2.trivial_terminal
-                        + internal::stats_prod2.ra.runs
-                        + internal::stats_prod2.pq.runs;
```
```
     uintwide total_runs = internal::stats_prod2.trivial_file
+                        + internal::stats_prod2.trivial_terminal + internal::stats_prod2.ra.runs
+                        + internal::stats_prod2.pq.runs;
```

**Comment by SSoelvsten** [comment]
I think I have exhausted all observations on its changes (noted above). Overall, it looks really good! Most of the changes a perfect and makes older code align with styling I've adopted recently as I've learned more things.

**Review by SSoelvsten — CHANGES_REQUESTED** [review]
I think I have exhausted all observations on its changes (noted above). Overall, it does a great job! Most of the changes makes older code align with styling I've adopted recently but not applied everywhere.

If any of the above can be addressed, then that would be greatly appreciated.

**Comment by SSoelvsten** [comment]
To integrate *clang-format* with *CMake* add the following file

*./cmake/clang-cxx-dev-tools.cmake*:
```cmake
# Slight variation on:
#   https://www.labri.fr/perso/fleury/posts/programming/using-clang-tidy-and-clang-format.html

# Get all src/ files
file(GLOB_RECURSE ALL_SRC_FILES
  ${PROJECT_SOURCE_DIR}/src/*.[chi]pp
  ${PROJECT_SOURCE_DIR}/src/*.[chi]xx
  ${PROJECT_SOURCE_DIR}/src/*.cc
  ${PROJECT_SOURCE_DIR}/src/*.hh
  ${PROJECT_SOURCE_DIR}/src/*.ii
  ${PROJECT_SOURCE_DIR}/src/*.[CHI]
)

# Get all test/ files
file(GLOB_RECURSE ALL_TEST_FILES
  ${PROJECT_SOURCE_DIR}/test/*.[chi]pp
  ${PROJECT_SOURCE_DIR}/test/*.[chi]xx
  ${PROJECT_SOURCE_DIR}/test/*.cc
  ${PROJECT_SOURCE_DIR}/test/*.hh
  ${PROJECT_SOURCE_DIR}/test/*.ii
  ${PROJECT_SOURCE_DIR}/test/*.[CHI]
)

# Adding clang-format target if executable is found
find_program(CLANG_FORMAT "clang-format")
if(CLANG_FORMAT)
  add_custom_target(
    clang-format
    COMMAND /usr/bin/clang-format
    ${ALL_SRC_FILES} ${ALL_TEST_FILES}
    -i
  )
endif()

# Adding clang-tidy target if executable is found
find_program(CLANG_TIDY "clang-tidy")
if(CLANG_TIDY)
  add_custom_target(
    clang-tidy
    COMMAND /usr/bin/clang-tidy
    ${ALL_SRC_SOURCE_FILES} ${ALL_TEST_SOURCE_FILES}
    -config=''
    --
    -std=c++11
    ${INCLUDE_DIRECTORIES}
  )
endif()
```

Then add the following to the root-directory *CMakeLists.txt*

```cmake
# ============================================================================ #
# Formatting
# ============================================================================ #
include(cmake/clang-cxx-dev-tools.cmake)
```

Finally, add the following to the *makefile* to hide CMake.
```makefile
# ============================================================================ #
#  CLANG TOOLS
# ============================================================================ #
clang/format:
	@mkdir -p build/ && cd build/ && cmake -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) ..
	@cd build/ && make clang-format
```

**Pull request merged**
